export const formFields = {
    personalInformation: {
        title: 'Tell us about yourself...',
        description:
            'Dont worry, your personal details are only needed so we can get to know you and complete your application. Your information will only ever be shared with those who are working on your application.',
        sections: [
            {
                title: '',
                fields: [
                    {
                        title: '',
                        label: 'Title',
                        id: 'title',
                        type: 'buttons',
                        required: true,
                        columns: 4,
                        options: [
                            { name: 'Mr', value: 'mr' },
                            { name: 'Mrs', value: 'mrs' },
                            { name: 'Miss', value: 'miss' },
                            { name: 'Other', value: 'other' },
                        ],
                    },
                    {
                        firstName: '',
                        label: 'First Name',
                        id: 'firstName',
                        type: 'input',
                        inputType: 'text',
                        required: true,
                        warningText: 'Valid name is required',
                    },
                    {
                        lastName: '',
                        label: 'Last Name',
                        id: 'lastName',
                        type: 'input',
                        inputType: 'text',
                        required: true,
                        warningText: 'Valid last name is required',
                    },
                    {
                        birthDate: '',
                        label: 'Date of Birth',
                        id: 'dateOfBirth',
                        type: 'input',
                        inputType: 'text',
                        format: 'date',
                        validator: /^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\d\d$/,
                        required: true,
                        warningText: 'Valid date format is required (DD/MM/YYYY)',
                    },
                    {
                        email: '',
                        label: 'Email',
                        id: 'mail',
                        type: 'input',
                        inputType: 'text',
                        required: true,
                        warningText: 'Valid email is required',
                    },
                    {
                        mobileNumber: '',
                        label: 'Mobile Number',
                        id: 'mobileNumber',
                        type: 'input',
                        inputType: 'number',
                        required: true,
                        validator: /^([0][7])/,
                        warningText: 'Valid mobile number is required (starts with 07)',
                    },
                    {
                        homeNumber: '',
                        label: 'Home Number',
                        id: 'homeNumber',
                        type: 'input',
                        inputType: 'number',
                        required: false,
                    },
                    {
                        interest: '',
                        label: 'What are you looking to shop',
                        id: 'interest',
                        type: 'select',
                        required: true,
                        placeholder: 'Please select...',
                        warningText: 'Valid mobile number is required (starts with 07)',
                        options: [
                            { name: 'Instruments', value: 'instruments' },
                            { name: 'Jewelry', value: 'jewelry' },
                            { name: 'Electronics', value: 'electronics' },
                        ],
                    },
                ],
            },
        ],
    },
    income: {
        title: "Let's talk money...",
        description:
            "We know it's a little bit awkward, but we need this information so we can paint a picture about your life, work and finances. We'd recommend you look back over your previous bank statements to jog your memory if you're unsure, as it's important that this bit is as accurate as possible.",
        sections: [
            {
                title: '',
                fields: [
                    {
                        label: 'Employment Status',
                        id: 'status',
                        value: '',
                        type: 'buttons',
                        required: true,
                        columns: 2,
                        options: [
                            { name: '0 Time', value: 'fullTime' },
                            { name: 'Part Time', value: 'partTime' },
                            { name: 'Self-Employed', value: 'selfEmployed' },
                            { name: 'Not Employed', value: 'notEmployed' },
                            { name: 'Retired', value: 'retired' },
                            { name: 'Student', value: 'student' },
                            { name: 'Military', value: 'military' },
                            { name: 'Houseperson', value: 'houseperson' },
                        ],
                    },
                    {
                        label: 'Monthly Income',
                        id: 'monthlyIncome',
                        value: '',
                        type: 'input',
                        inputType: 'number',
                        is_currency: true,
                        currency: '£',
                        required: true,
                    },
                    {
                        label: 'Income Frequency',
                        id: 'status',
                        value: '',
                        type: 'buttons',
                        required: true,
                        columns: 2,
                        options: [
                            { name: 'Weekly', value: 'weekly' },
                            { name: 'Monthly', value: 'monthly' },
                            { name: 'Other', value: 'other' },
                        ],
                    },
                ],
            },
            {
                title: 'Outgoings',
                fields: [
                    {
                        label: 'Number of Financial Dependants',
                        id: 'financialDependants',
                        value: '',
                        type: 'buttons',
                        required: true,
                        columns: 4,
                        options: [
                            { name: '0', value: '0' },
                            { name: '1', value: '1' },
                            { name: '2', value: '2' },
                            { name: '+3', value: '+3' },
                        ],
                    },
                    {
                        label: 'Monthly Mortgage of Rent Amount',
                        id: 'monthlyMortgage',
                        value: '',
                        type: 'input',
                        inputType: 'number',
                        is_currency: true,
                        currency: '£',
                        required: true,
                    },
                    {
                        label: 'Monthly Spending Total',
                        id: 'monthlyTotalSpending',
                        value: '',
                        type: 'input',
                        inputType: 'number',
                        is_currency: true,
                        currency: '£',
                        required: true,
                    },
                    {
                        label: '',
                        description:
                            'I confirm that I do not expect my financial situation to get worse beyond the cost of living rises that we are already aware of and agree that by submitting this application a <b>soft search</b> will be performed on my credit file. *',
                        id: 'confirm',
                        value: false,
                        type: 'checkbox',
                        required: true,
                    },
                ],
            },
        ],
    },
};

export default {
    formFields,
};
